base/api/urls.py
from django.urls import path
from base.api import views
urlpatterns =[
    path('', views.getRoutes),
    path('rooms/', views.getRooms),
    path('rooms/<str:pk>/', views.getRoom),
    path('topic/', views.getTopic),
    path('users/', views.getUser),
    


    
    
    
]

base/urls.py
from django.urls import path
from base import views

#  list of url patterns  : 
urlpatterns = [
    path('login/', views.loginPage, name='login_user'),
    path('logout/', views.logoutPage, name = 'logout_user'),
    path('register/', views.registerPage, name = 'register_user'),
    path('update-user/', views.updateUser, name = 'update-user'),
    
    

    path('', views.home, name = 'home'),
    path('room/<str:pk>/',views.room, name= 'room'),
    path('crate-room/', views.createRoom, name='create-room'),
    path('update-room/<int:pk>/', views.updateRoom, name='update-room'),
    path('delete-room/<int:pk>/', views.deleteRoom, name='delete-room'),

    path('delete-message/<int:pk>/', views.deleteMessge , name = 'delete-message'),
    path('profile/<str:pk>/', views.userProfile, name = 'user-profile'),
    path('browse-topics/', views.browseTopics, name='browse-topics'),
    path('recent-activity/', views.recentActivity, name='recent-activity'),


    # path('user-profile/<int:pk>/', views.userProfile, name = 'userprofile'),


    
    


   


]

studybud/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings


#  This is our project url : 
urlpatterns = [
    path('admin/', admin.site.urls),  
    path('', include('base.urls')),
    path('api/', include('base.api.urls')),
    
    

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models
from django.contrib.auth.models import User
from django.templatetags.static import static
# Create your models here.
# Here we creating the database table using the python classes : 


class Topic(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self) -> str:
        return self.name
    


class Room(models.Model):
    # if the Topic  is defined after the 'Room' we can still use the room, using string specification : like this 'Room' 
    host = models.ForeignKey(User, on_delete= models.CASCADE, null=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    # adding  the participants , and it will be the many  to many fields 
    participants = models.ManyToManyField(User,related_name='participants' , null=True)
    updated = models.DateTimeField(auto_now=True)
    created  = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self) -> str:
        return self.name
    

class Message(models.Model):

    # one to many relationship 
    user = models.ForeignKey(User, on_delete= models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name='messages')
    body = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    created  = models.DateTimeField(auto_now_add=True)


    def __str__(self) -> str:
        return self.body[0:40]
    
    
    class Meta:
        ordering = ['-updated', '-created']





class Profile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # upload_to specify where i want to add these images, == upload_to='profile_images/'
    image = models.ImageField(null=True, blank=True, upload_to='profile_images/')
    bio = models.TextField(null=True, blank=True)


    def get_image_url(self):
        if self.image:
            return self.image.url
        else:
            return static('images/my.jpg')
        

    def __str__(self) -> str:
        return self.bio[0:20]
    


    


class kon(models.Model):
    one = models.IntegerField()

base/api/views.py
from rest_framework.decorators import api_view
from rest_framework.response import Response
from base.models import Room, Topic
from .serializers import RoomSerailizer, UserSerialize
from django.contrib.auth.models import User

@api_view(['GET'])
def getRoutes(request):
    
    context = [
        'GET /api',
        'GET /api/rooms',
        'GET /api/rooms/:id',
        'GET /api/topic',
        'GET /api/user', 




    ]

    return Response(context)

@api_view(['GET'])
def getRooms(request):
    rooms = Room.objects.all()
    serializer = RoomSerailizer(rooms, many=True)
 
    return Response(serializer.data)




@api_view(['GET'])
def getRoom(request,pk):
    room = Room.objects.get(pk =pk)
    # the many parameter is for multiple object, here in this case there is single object so that many is false : 

    serializer = RoomSerailizer(room, many =False)
    return Response(serializer.data)


@api_view(['GET', 'POST']) # so thi is the function decorator for creating the api  and the 'method we want the requested user can make are also mention here' 
def getTopic(request):

    somewhere = {
        'locatioin': 'India', 

    }
    return Response(somewhere)


@api_view(['GET'])
def getUser(request):

    user = User.objects.all()
    users = UserSerialize(user, many =True)
    return Response(users.data)

base/views.py
from django.shortcuts import render
# lookup method : for multiple value in serach bar : , depdending on the base value in dynamic: 
from django.db.models import Q
from django.http import HttpResponse
# Create your views here.
from base.models import Room, Topic
from base.form import RoomFrom, UserForm
from django.shortcuts import redirect
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout 
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from base.models import Message

from .models import Profile
from .form import ProfileForm





from base.form import MessageForm

def loginPage(request):
    page = 'login'
    # restricting user to login again , if they are login : 
    if request.user.is_authenticated:
        return HttpResponse('you are already login : ')
    

    if request.method == "POST":
        username = request.POST.get('username').lower()
        password = request.POST.get('password')

        try:
            # getting the user 
            user = User.objects.get(username = username)

        except :
            messages.error(request, 'The user is not exits in the Registeration : ')
        user = authenticate(request, username = username, password = password)
        if user is not None:
            login(request,user=user)
            return redirect('home')
        else:
            messages.info(request,'username and password does not exits :')
        
    return render(request, 'base/regi_login.html',{'page':page})


def logoutPage(request):
    logout(request)
    return redirect('home')

def registerPage(request):
    page = 'register'
    form = UserCreationForm()

    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            # we just create this not saving at all : 

          


            
            user.save()
            profile = Profile.objects.create(user = user )
            # automatically login the user , in the website : 
            login(request, user)
            return redirect('home')
        else: 
            messages.error(request, 'The Form is invalid : ')
            return redirect('register_user')
        
    return render(request, 'base/regi_login.html', {'page': page, 'form': form})



def home(request):  
    room = Room.objects.all()
    topic  = Topic.objects.all()
    room_count = room.count()
    q  = request.GET.get('q') if request.GET.get('q') else ''
    room = Room.objects.filter(Q(topic__name__icontains = q)
                               | Q(name__icontains=q) 
                               | Q(description__icontains=q  ))

    

    room_messages = Message.objects.filter(Q(room__name__icontains =q),
                                           Q(room__topic__name__icontains =q))
    

    context = {
        'rooms': room[0:3],
        'topics': topic[:9],
        'room_count': room_count,
        'room_messages': room_messages[0:3],
    





    }
    
    return render(request, 'base/home.html',context )



def room(request, pk ):
    
    room =Room.objects.get(pk = int(pk) )
    # we can query up to the the childe model like this : 
    # messages = room.message_set.all(), message is model name 
    # --- or we can use the relative name attribute specify in the model 
    messages = room.messages.all().order_by('-created')
    # accesing the participants 
    participants = room.participants.all()

    if request.method == 'POST':
     message = Message.objects.create(
         user = request.user,
         room = room,
         body = request.POST.get('body') 
     )
     # this is the way we can add the user in the participants list :
     room.participants.add(request.user)
     
     return redirect('room' , pk=room.id )
    


    context = {
        'room': room, 
        'room_messages': messages, 
        'participants':  participants,


    }

    return render(request, 'base/room.html', context)


def userProfile(request,pk):
    user = User.objects.get(pk = int(pk))

    
    # message =Message.objects.filter(user = user )
    message  = user.message_set.all()
    # topics = Topic.objects.filter(room__host = user )[0:5]
    room_count = Room.objects.filter(host = user).count()
    
    topics = set(Topic.objects.filter(room__host = user)    )

    print('the value of the count',room_count)

    q  = request.GET.get('q') if request.GET.get('q') else ''
    rooms = Room.objects.filter(Q(topic__name__icontains = q)
                               | Q(name__icontains=q) 
                               | Q(description__icontains=q  )).filter(host = user)
    

    message = Message.objects.filter(Q(room__name__icontains =q),
                                           Q(room__topic__name__icontains =q)).filter(user = user )
    
 


    context = {
        'user': user,
        'rooms': rooms,
        'room_messages': message , 
        'topics': topics, 
        'room_count': room_count, 
        'next': 'profile',
        



    }
    return render(request, 'base/profile.html', context )



@login_required
def updateUser(request ):
    user = request.user
    
    

    userform = UserForm(instance=user)
    profile = ProfileForm(instance=user.profile)




    if request.method == "POST":
        userform = UserForm(request.POST, instance=user)
        profileform = ProfileForm(request.POST, request.FILES)

        if userform.is_valid() and profileform.is_valid():
            # you have to check here : 
            ok = userform.save(commit=False)
            ok.username = userform.cleaned_data['username'].lower()
        
            ok.save()
            profile, created  = Profile.objects.get_or_create(user = request.user)
            profile.user = request.user
            profile.image = profileform.cleaned_data['image']
            profile.bio = profileform.cleaned_data['bio']


            profile.save()
            print('ave it ')

            return redirect('user-profile', user.id)
        else: 
            messages.info(request, 'the data is wrong ')
            return redirect('update-user')
    

    context ={
        'userform': userform, 
        'profileform':profile,


        
    }
    return render(request, 'base/update_user.html', context )







@login_required
def createRoom(request):
    room = RoomFrom()
    topics = Topic.objects.all()

    if request.method == "POST":
        topic_name = request.POST.get('topic')  
        # the use of the get or create 
        topic, created  = Topic.objects.get_or_create(name=topic_name)

        
        Room.objects.create(
            host = request.user,
            topic = topic,
            name = request.POST.get('name'),
            description = request.POST.get('description'),
            
        )
        print('yeah')
        return redirect('home')
        
        
    context ={
        'form': room,
        'topics': topics,
        
    }
    return render(request, 'base/room_form.html', context)

@login_required
def updateRoom(request, pk ):
    room =Room.objects.get(pk = pk )
    # The initial instance for the predefined data in the form : 
    form = RoomFrom(instance=room)
    topics = Topic.objects.all()

    if request.user!= room.host:
        return HttpResponse(f'Hey {request.user} . You are not allowed to do that , becuase its "{room.host}" room ')
    
    if request.method == 'POST':
        topic_name = request.POST.get('topic')  
        # the use of the get or create 
        topic, created  = Topic.objects.get_or_create(name=topic_name)


        room.name = request.POST.get('name')
        room.topic = topic
        room.description = request.POST.get('description')
        room.save()
        return redirect('home')
     



    
    context = {
        'form': form, 
        'topics': topics,
        'room':room, 
        


    }
    return render(request, 'base/room_form.html', context)
@login_required
def deleteRoom(request, pk ):
    room = Room.objects.get(pk=pk)
    if request.user!= room.host:
        return HttpResponse(f'Hey {request.user} . You are not allowed to do that , becuase its "{room.host}" room ')
    if request.method == 'POST':
        room.delete()
        return redirect('home')
    
    return render(request, 'base/delete.html' , {'obj': room})


# deleting the message : 
@login_required
def deleteMessge(request,pk):
    message = Message.objects.get(pk=pk)
    if request.user!= message.user:
        return HttpResponse(f'Hey {request.user} . You are not allowed to do that , becuase its "{message.user}" room ')
    if request.method == 'POST':
        message.delete()
        return redirect('home')
    
    return render(request, 'base/delete.html' , {'obj': message})



def browseTopics(request):
    
    room_count = Room.objects.all().count()

    q = request.GET.get('q') if request.GET.get('q') else ''
    if q:
        topics = Topic.objects.filter(name__icontains =q)

    else:
        topics  = Topic.objects.all()[0:5]



    context = {
        'topics': topics,
        'room_count': room_count

    }
    
    return render(request, 'base/topics.html', context )



def recentActivity(request):
    activites = Message.objects.all().order_by('-pk')

    context = {
        'activites': activites[:3] 

    }
    
    return render(request, 'base/activity.html', context )

base/templates/base/activity.html
{% extends 'main.html' %}
{% block content %}
{% load static  %}
    <main class="layout">
      <div class="container">
        <div class="layout__box">
          <div class="layout__boxHeader">
            <div class="layout__boxTitle">
              <a href="{% url 'home' %}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>arrow-left</title>
                  <path
                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
                  ></path>
                </svg>
              </a>
              <h3>Recent Activities</h3>
            </div>
          </div>

          {% for activity in activites %}
          <div class="activities-page layout__body">
            <div class="activities__box">
              <div class="activities__boxHeader roomListRoom__header">
                <a href="{% url 'user-profile' activity.user.id %}" class="roomListRoom__author">
                  <div class="avatar avatar--small">
                    <img src="https://randomuser.me/api/portraits/women/11.jpg" />
                  </div>
                  <p>
                    @{{activity.user.email}}
                    <span>{{activity.created}} ago</span>
                  </p>
                </a>
                <div class="roomListRoom__actions">
                  <a href="{% url 'delete-message' activity.id %}">
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                      <title>remove</title>
                      <path
                        d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                      ></path>
                    </svg>
                  </a>
                </div>
              </div>
              <div class="activities__boxContent">
                <p>replied to post “<a href="{%  url 'room' activity.room.id %}">{{activity.room.topic.name}}!</a>”</p>
                <div class="activities__boxRoomContent">
                  {{activity.body}}
                </div>
              </div>
            </div>

          </div>
          {% endfor %}
        </div>
      </div>
    </main>
{% endblock %}

base/templates/base/activity_component.html
{% load static %}

{% for message in room_messages  %}
<div class="activities__box">
    <div class="activities__boxHeader roomListRoom__header">
      <a href="{% url 'user-profile' message.user.id %}" class="roomListRoom__author">
        <div class="avatar avatar--small">
          <img src="{% static 'images/my.jpg' %}" alt="not " />
        </div>
        <p>           
          {{message.user}}
          <span>{{message.created|timesince}}  ago</span>
        
        </p>

      </a>
      <div class="roomListRoom__actions">
        {% if request.user == message.user %}
        <a href="{% url 'delete-message' message.id %}">
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
            <title>remove</title>
            <path
              d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
            ></path>
          </svg>
        </a>
        {% endif %}
      </div>
    </div>
    <div class="activities__boxContent">
      <p>replied to post “<a href="{% url 'room' message.room.id %}">{{message.room}}</a>”</p>
      <div class="activities__boxRoomContent">
            {{message.body}}
      </div>
    </div>
  </div>
  {% endfor %}

base/templates/base/delete.html
{% extends 'main.html' %}
{% load static %}

{% block content %}

    <main class="delete-item layout">
        <div class="container">
            <div class="layout__box">
                <div class="layout__boxHeader">
                    <div class="layout__boxTitle">
                        <a href="{{request.META.HTTP_REFERER}}">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                viewBox="0 0 32 32">
                                <title>arrow-left</title>
                                <path
                                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                                </path>
                            </svg>
                        </a>
                        <h3>Back</h3>
                    </div>
                </div>
                <div class="layout__body">
                    <form class="form" action="#" method="post">
                        {% csrf_token %}
                        <div class="form__group">
                            <p>Are you sure you want to delete "{{obj}}"?</p>
                        </div>

                        <div class="for__group">
                            <input class="btn btn--main" type="submit" value="Confirm" />
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </main>
    <script src="{% static 'js/script.js' %}"></script>
{%  endblock %}

base/templates/base/edit-user.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" href="assets/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="style.css" />
    <title>StudyBuddy - Find study partners around the world!</title>
  </head>

  <body>
    <header class="header header--loggedIn">
      <div class="container">
        <a href="/" class="header__logo">
          <img src="assets/logo.svg" />
          <h1>StudyBuddy</h1>
        </a>
        <form class="header__search">
          <label>
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>search</title>
              <path
                d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
              ></path>
            </svg>
            <input placeholder="Search for posts" />
          </label>
        </form>
        <nav class="header__menu">
          <!-- Not Logged In -->
          <!-- <a href="/login.html">
            <img src="./assets/avatar.svg" />
            <p>Account</p>
          </a> -->

          <!-- Logged In -->
          <a href="#">
            <div class="avatar avatar--medium active">
              <img src="https://randomuser.me/api/portraits/men/37.jpg" />
            </div>
            <p>John Doe <span>@john_doe</span></p>
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>chevron-down</title>
              <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
            </svg>
          </a>
        </nav>
      </div>
    </header>

    <main class="update-account layout">
        <div class="container">
            <div class="layout__box">
                <div class="layout__boxHeader">
                    <div class="layout__boxTitle">
                        <a href="profile.html">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                viewBox="0 0 32 32">
                                <title>arrow-left</title>
                                <path
                                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                                </path>
                            </svg>
                        </a>
                        <h3>Edit your profile</h3>
                    </div>
                </div>
                <div class="layout__body">
                    <form class="form" action="#">
                        <div class="form__group">
                            <label for="profile_pic">Avatar</label>
                            <input id="profile_pic" name="profile_pic" type="file" />
                        </div>

              <div class="form__group">
                <label for="username">Username</label>
                <input id="username" name="username" type="text" placeholder="E.g. John doe" />
              </div>

              <div class="form__group">
                <label for="email">Email</label>
                <input id="email" name="email" type="text" placeholder="E.g. john@email.com" />
              </div>

                        <div class="form__group">
                            <label for="user_bio">Bio</label>
                            <textarea name="user_bio" id="user_bio" placeholder="Write about yourself..."></textarea>
                        </div>
                        <div class="form__action">
                            <a class="btn btn--dark" href="index.html">Cancel</a>
                            <button class="btn btn--main" type="submit">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
      </div>
    </main>
  </body>
</html>

base/templates/base/home.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
    <main class="layout layout--3">
      <div class="container">
        <!-- Topics Start -->

        {% include 'base/topics_component.html' %}
       
        <!-- Topics End -->

        <!-- Room List Start -->
        <div class="roomList">
          <div class="mobile-menu">
            <form class="header__search" method="get" action="{% url 'home' %}">
              
              <label>
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>search</title>
                  <path
                    d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
                  ></path>
                </svg>
                <input placeholder="Search for posts"  name="q"/>
              </label>
            </form>
            <div class="mobile-menuItems">
              <a class="btn btn--main btn--pill" href="{% url 'browse-topics' %}">Browse Topics</a>
              <a class="btn btn--main btn--pill" href="{% url 'recent-activity' %}">Recent Activities</a>
            </div>
          </div>
          <div class="roomList__header">
            <div>
              <h2>Study Room</h2>
              <p>{{room_count}} Rooms available</p>
            </div>

            <a class="btn btn--main" href="{% url 'create-room' %}">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>add</title>
                <path
                  d="M16.943 0.943h-1.885v14.115h-14.115v1.885h14.115v14.115h1.885v-14.115h14.115v-1.885h-14.115v-14.115z"
                ></path>
              </svg>
              Create Room
            </a>
          </div>
        {% include 'base/room_component.html' %}
        </div>
        <!-- Room List End -->

        <!-- Activities Start -->
        <div class="activities">
          <div class="activities__header">
            <h2>Recent Activities</h2>
          </div>
          {% include 'base/activity_component.html' %}
        </div>
        <!-- Activities End -->
      </div>
    </main>
   
    {% endblock %}

base/templates/base/topics.html
{% extends 'main.html' %}
{% block content %}
    <main class="create-room layout">
      <div class="container">
        <div class="layout__box">
          <div class="layout__boxHeader">
            <div class="layout__boxTitle">
              <a href="{% url 'home' %}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>arrow-left</title>
                  <path
                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
                  ></path>
                </svg>
              </a>
              <h3>Browse Topics</h3>
            </div>
          </div>

          <div class="topics-page layout__body">
            <form class="header__search" action="{% url 'browse-topics' %}" method="get">
              <label>
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>search</title>
                  <path
                    d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
                  ></path>
                </svg>
                <input placeholder="Search for posts" name="q"/>

              </label>
            </form>

            <ul class="topics__list">
              <li>
                <a href="{% url 'home'  %}">All  <span>{{room_count}}</span></a>
              </li>
              {% for topic in topics %}
              {% if  next == 'profile' %}
                <li>
                  <a href="{% url 'user_profile' topic.room.host.id   %}?q={{topic.name}}">{{topic.name}} <span>{{topic.room_set.all.count}}</span></a>
                </li>
              {% else %}

              <li>
                <a href="{% url 'home'  %}?q={{topic.name}}">{{topic.name}} <span>{{topic.room_set.all.count}}</span></a>
              </li>
              {% endif %}
              {% endfor %}


            </ul>
          </div>
        </div>
      </div>
    </main>
{% endblock %}

base/templates/base/topics_component.html
<div class="topics">
    <div class="topics__header">
      <h2>Browse Topics</h2>
    </div>
    <ul class="topics__list">
    
      <li>
        <a href="{% url 'home' %}" class="active">All <span>{{room_count}}</span></a>
      </li>

      {% for topic in topics %}
      {% if next == 'profile' %}
      <li>
        <a href="{% url 'user-profile' user.id  %}?q={{topic.name}}">{{topic.name}} <!-- <span>{{topic.room_set}}</span>   --> </a>
      </li>
      {% else %}
      <li>
   
         <a href="{% url 'home' %}?q={{topic.name}}">{{topic.name}}  <span>{{ topic.room_set.all.count }}</span> </a>
        
      </li>
      {% endif %}
    {% endfor %}
      
    </ul>
    <a class="btn btn--link" href="{% url 'browse-topics' %}">
      More
      <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
        <title>chevron-down</title>
        <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
      </svg>
    </a>
  </div>